version: "2"

linters:
  disable:
    - errcheck
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "SA1019:"
      - linters:
          - staticcheck
        text: "S1040:"
