-- name: BackfillAttentionSessions :many
SELECT COALESCE(stream.session_id, attachment.target_session_id) AS session_id FROM session_event_streams AS stream FULL JOIN session_attachments AS attachment ON attachment.target_session_id = stream.session_id LEFT JOIN session_attention_summaries AS summary ON summary.session_id = COALESCE(stream.session_id, attachment.target_session_id) WHERE COALESCE(stream.session_id, attachment.target_session_id) > sqlc.arg(after_session_id) AND (summary.session_id IS NULL OR summary.projection_state = 'incomplete' OR summary.latest_seq <> COALESCE(stream.latest_seq, 0)) ORDER BY COALESCE(stream.session_id, attachment.target_session_id) ASC LIMIT sqlc.arg(session_limit);
-- name: AttentionBackfillCheckpointExists :one
SELECT EXISTS (SELECT 1 FROM session_event_streams AS checkpoint_stream WHERE checkpoint_stream.session_id = sqlc.arg('checkpoint_session_id') UNION SELECT 1 FROM session_attachments AS checkpoint_attachment WHERE checkpoint_attachment.target_session_id = sqlc.arg('checkpoint_session_id')) AND NOT EXISTS (SELECT 1 FROM session_event_streams AS stream FULL JOIN session_attachments AS attachment ON attachment.target_session_id = stream.session_id LEFT JOIN session_attention_summaries AS summary ON summary.session_id = COALESCE(stream.session_id, attachment.target_session_id) WHERE COALESCE(stream.session_id, attachment.target_session_id) < sqlc.arg('checkpoint_session_id') AND (summary.session_id IS NULL OR summary.projection_state = 'incomplete' OR summary.latest_seq <> COALESCE(stream.latest_seq, 0)));
-- name: BackfillAttentionEvents :many
SELECT session_id, seq, (CASE WHEN octet_length(payload::text) > 1048576 THEN 'permission.request' ELSE type END)::text AS type, (CASE WHEN octet_length(payload::text) > 1048576 THEN '{}'::jsonb ELSE payload END)::jsonb AS payload, created_at FROM session_events WHERE session_id = sqlc.arg(session_id) AND seq > sqlc.arg(after_seq) ORDER BY seq ASC LIMIT sqlc.arg(event_limit);
-- name: BackfillAttentionLedger :one
SELECT MAX(created_at)::TIMESTAMPTZ AS last_client_command_at, COUNT(*)::BIGINT AS command_count, COUNT(*) FILTER (WHERE status = 'outcome_unknown')::BIGINT AS outcome_unknown_count FROM session_pending_commands WHERE session_id = sqlc.arg(session_id);
-- name: BackfillAttentionStream :one
SELECT latest_seq, retention_gap, updated_at FROM session_event_streams WHERE session_id = sqlc.arg(session_id);
-- name: BackfillAttentionAttachment :one
SELECT status, delivery_state, delivery_version, queue_reason, expires_at, blocking_session_id FROM session_attachments WHERE target_session_id = sqlc.arg(session_id);
-- name: ResetAttentionForBackfill :one
UPDATE session_attention_summaries SET state = 'starting', permission_id = NULL, permission_status = NULL, terminal_outcome = NULL, latest_change_seq = NULL, last_durable_event_at = NULL, last_client_command_at = NULL, blocker_kind = NULL, blocker_reason = NULL, blocker_expires_at = NULL, blocking_session_id = NULL, blocker_operation = NULL, summary_version = 0, projection_state = 'complete', updated_at = statement_timestamp() WHERE session_id = sqlc.arg(session_id) RETURNING latest_seq;
-- name: UpsertAttentionBackfillEvent :exec
INSERT INTO session_attention_summaries (session_id, latest_seq, state, permission_id, permission_status, terminal_outcome, latest_change_seq, last_durable_event_at, projection_state) VALUES (sqlc.arg(session_id), sqlc.arg(latest_seq), COALESCE(sqlc.narg(event_state), 'starting'), sqlc.narg(permission_id)::TEXT, CASE WHEN sqlc.narg(permission_id)::TEXT IS NULL THEN NULL ELSE 'pending' END, sqlc.narg(terminal_outcome)::TEXT, sqlc.arg(latest_change_seq), sqlc.arg(event_time), CASE WHEN sqlc.arg(projection_incomplete)::BOOLEAN THEN 'incomplete' ELSE 'complete' END) ON CONFLICT (session_id) DO UPDATE SET latest_seq = GREATEST(session_attention_summaries.latest_seq, EXCLUDED.latest_seq), state = COALESCE(sqlc.narg(event_state), session_attention_summaries.state), permission_id = CASE WHEN NOT sqlc.arg(permission_change)::BOOLEAN THEN session_attention_summaries.permission_id WHEN sqlc.narg(permission_id)::TEXT IS NOT NULL THEN sqlc.narg(permission_id)::TEXT WHEN session_attention_summaries.permission_id = sqlc.narg(permission_decision_id)::TEXT THEN NULL ELSE session_attention_summaries.permission_id END, permission_status = CASE WHEN NOT sqlc.arg(permission_change)::BOOLEAN THEN session_attention_summaries.permission_status WHEN sqlc.narg(permission_id)::TEXT IS NOT NULL THEN 'pending' WHEN session_attention_summaries.permission_id = sqlc.narg(permission_decision_id)::TEXT THEN NULL ELSE session_attention_summaries.permission_status END, terminal_outcome = COALESCE(session_attention_summaries.terminal_outcome, sqlc.narg(terminal_outcome)::TEXT), latest_change_seq = COALESCE(EXCLUDED.latest_change_seq, session_attention_summaries.latest_change_seq), last_durable_event_at = EXCLUDED.last_durable_event_at, projection_state = CASE WHEN session_attention_summaries.projection_state = 'incomplete' OR sqlc.arg(projection_incomplete)::BOOLEAN THEN 'incomplete' ELSE session_attention_summaries.projection_state END, updated_at = statement_timestamp();
-- name: FinalizeAttentionBackfill :exec
UPDATE session_attention_summaries SET projection_state = CASE WHEN sqlc.arg(retention_gap)::BOOLEAN OR sqlc.arg(projection_incomplete)::BOOLEAN THEN 'incomplete' ELSE projection_state END, updated_at = statement_timestamp() WHERE session_id = sqlc.arg(session_id);
-- name: RestoreAttentionBackfillActivity :exec
UPDATE session_attention_summaries SET last_durable_event_at = sqlc.arg(last_durable_event_at), updated_at = statement_timestamp() WHERE session_id = sqlc.arg(session_id);
-- name: RestoreAttentionBackfillAttachment :exec
UPDATE session_attention_summaries SET blocker_kind = sqlc.narg(blocker_kind), blocker_reason = sqlc.narg(blocker_reason), blocker_expires_at = sqlc.narg(blocker_expires_at), blocking_session_id = sqlc.narg(blocking_session_id), blocker_operation = sqlc.narg(blocker_operation), projection_state = 'incomplete', updated_at = statement_timestamp() WHERE session_id = sqlc.arg(session_id);
-- name: EnsureAttentionBackfillSummary :exec
INSERT INTO session_attention_summaries (session_id, latest_seq, state, summary_version, last_client_command_at, projection_state) VALUES (sqlc.arg(session_id), sqlc.arg(latest_seq), 'starting', sqlc.arg(summary_version), sqlc.narg(last_client_command_at), 'incomplete') ON CONFLICT (session_id) DO NOTHING;
-- name: RestoreAttentionBackfillLedger :exec
UPDATE session_attention_summaries SET summary_version = GREATEST(summary_version, sqlc.arg(summary_version)::BIGINT), last_client_command_at = sqlc.narg(last_client_command_at), blocker_kind = CASE WHEN sqlc.arg(has_outcome_unknown)::BOOLEAN THEN 'outcome_unknown' ELSE blocker_kind END, blocker_reason = NULL, blocker_expires_at = NULL, blocking_session_id = NULL, blocker_operation = CASE WHEN sqlc.arg(has_outcome_unknown)::BOOLEAN THEN 'command' ELSE NULL END, updated_at = statement_timestamp() WHERE session_id = sqlc.arg(session_id);
