// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adapter_connections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptAdapterHello = `-- name: AcceptAdapterHello :one
UPDATE session_adapter_connections
SET connection_epoch = connection_epoch + 1,
    accepted_fence = nextval('session_adapter_connection_accepted_fence_seq'),
    updated_at = clock_timestamp()
WHERE session_id = $1
  AND active_credential_generation = $2
  AND active_credential_expires_at > clock_timestamp()
  AND revoked_at IS NULL
  AND terminal_at IS NULL
RETURNING session_id, connection_epoch, accepted_fence, active_credential_generation, credential_generation_high_watermark, active_credential_expires_at, pending_credential_generation, pending_credential_expires_at, prior_recovery_credential_generation, rotation_id, revoked_at, terminal_at, created_at, updated_at
`

type AcceptAdapterHelloParams struct {
	SessionID            string
	CredentialGeneration int64
}

func (q *Queries) AcceptAdapterHello(ctx context.Context, arg AcceptAdapterHelloParams) (SessionAdapterConnection, error) {
	row := q.db.QueryRow(ctx, acceptAdapterHello, arg.SessionID, arg.CredentialGeneration)
	var i SessionAdapterConnection
	err := row.Scan(
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.AcceptedFence,
		&i.ActiveCredentialGeneration,
		&i.CredentialGenerationHighWatermark,
		&i.ActiveCredentialExpiresAt,
		&i.PendingCredentialGeneration,
		&i.PendingCredentialExpiresAt,
		&i.PriorRecoveryCredentialGeneration,
		&i.RotationID,
		&i.RevokedAt,
		&i.TerminalAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const activateAdapterCredential = `-- name: ActivateAdapterCredential :one
UPDATE session_adapter_connections
SET prior_recovery_credential_generation = active_credential_generation,
    active_credential_generation = pending_credential_generation,
    active_credential_expires_at = pending_credential_expires_at,
    pending_credential_generation = NULL,
    pending_credential_expires_at = NULL,
    rotation_id = NULL,
    connection_epoch = connection_epoch + 1,
    accepted_fence = nextval('session_adapter_connection_accepted_fence_seq'),
    updated_at = clock_timestamp()
WHERE session_id = $1
  AND active_credential_generation = $2
  AND connection_epoch = $3
  AND pending_credential_generation = $4
  AND rotation_id = $5
  AND active_credential_expires_at > clock_timestamp()
  AND pending_credential_expires_at > clock_timestamp()
  AND revoked_at IS NULL
  AND terminal_at IS NULL
RETURNING session_id, connection_epoch, accepted_fence, active_credential_generation, credential_generation_high_watermark, active_credential_expires_at, pending_credential_generation, pending_credential_expires_at, prior_recovery_credential_generation, rotation_id, revoked_at, terminal_at, created_at, updated_at
`

type ActivateAdapterCredentialParams struct {
	SessionID                string
	ExpectedActiveGeneration int64
	ExpectedEpoch            int64
	PendingGeneration        pgtype.Int8
	RotationID               pgtype.Text
}

func (q *Queries) ActivateAdapterCredential(ctx context.Context, arg ActivateAdapterCredentialParams) (SessionAdapterConnection, error) {
	row := q.db.QueryRow(ctx, activateAdapterCredential,
		arg.SessionID,
		arg.ExpectedActiveGeneration,
		arg.ExpectedEpoch,
		arg.PendingGeneration,
		arg.RotationID,
	)
	var i SessionAdapterConnection
	err := row.Scan(
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.AcceptedFence,
		&i.ActiveCredentialGeneration,
		&i.CredentialGenerationHighWatermark,
		&i.ActiveCredentialExpiresAt,
		&i.PendingCredentialGeneration,
		&i.PendingCredentialExpiresAt,
		&i.PriorRecoveryCredentialGeneration,
		&i.RotationID,
		&i.RevokedAt,
		&i.TerminalAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adapterConnectionByID = `-- name: AdapterConnectionByID :one
SELECT session_id, connection_epoch, accepted_fence, active_credential_generation, credential_generation_high_watermark, active_credential_expires_at, pending_credential_generation, pending_credential_expires_at, prior_recovery_credential_generation, rotation_id, revoked_at, terminal_at, created_at, updated_at FROM session_adapter_connections WHERE session_id = $1
`

func (q *Queries) AdapterConnectionByID(ctx context.Context, sessionID string) (SessionAdapterConnection, error) {
	row := q.db.QueryRow(ctx, adapterConnectionByID, sessionID)
	var i SessionAdapterConnection
	err := row.Scan(
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.AcceptedFence,
		&i.ActiveCredentialGeneration,
		&i.CredentialGenerationHighWatermark,
		&i.ActiveCredentialExpiresAt,
		&i.PendingCredentialGeneration,
		&i.PendingCredentialExpiresAt,
		&i.PriorRecoveryCredentialGeneration,
		&i.RotationID,
		&i.RevokedAt,
		&i.TerminalAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const initializeAdapterConnection = `-- name: InitializeAdapterConnection :one
INSERT INTO session_adapter_connections (
    session_id, connection_epoch, accepted_fence, active_credential_generation,
    credential_generation_high_watermark, active_credential_expires_at
)
SELECT $1, 0, 0, $2,
       $2, $3
WHERE $3::TIMESTAMPTZ > clock_timestamp()
ON CONFLICT (session_id) DO NOTHING
RETURNING session_id, connection_epoch, accepted_fence, active_credential_generation, credential_generation_high_watermark, active_credential_expires_at, pending_credential_generation, pending_credential_expires_at, prior_recovery_credential_generation, rotation_id, revoked_at, terminal_at, created_at, updated_at
`

type InitializeAdapterConnectionParams struct {
	SessionID        string
	ActiveGeneration int64
	ActiveExpiresAt  pgtype.Timestamptz
}

func (q *Queries) InitializeAdapterConnection(ctx context.Context, arg InitializeAdapterConnectionParams) (SessionAdapterConnection, error) {
	row := q.db.QueryRow(ctx, initializeAdapterConnection, arg.SessionID, arg.ActiveGeneration, arg.ActiveExpiresAt)
	var i SessionAdapterConnection
	err := row.Scan(
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.AcceptedFence,
		&i.ActiveCredentialGeneration,
		&i.CredentialGenerationHighWatermark,
		&i.ActiveCredentialExpiresAt,
		&i.PendingCredentialGeneration,
		&i.PendingCredentialExpiresAt,
		&i.PriorRecoveryCredentialGeneration,
		&i.RotationID,
		&i.RevokedAt,
		&i.TerminalAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const matchingInitialAdapterConnection = `-- name: MatchingInitialAdapterConnection :one
SELECT session_id, connection_epoch, accepted_fence, active_credential_generation, credential_generation_high_watermark, active_credential_expires_at, pending_credential_generation, pending_credential_expires_at, prior_recovery_credential_generation, rotation_id, revoked_at, terminal_at, created_at, updated_at FROM session_adapter_connections
WHERE session_id = $1
  AND connection_epoch = 0 AND accepted_fence = 0
  AND active_credential_generation = $2
  AND credential_generation_high_watermark = $2
  AND active_credential_expires_at = $3
  AND pending_credential_generation IS NULL AND prior_recovery_credential_generation IS NULL
  AND rotation_id IS NULL AND revoked_at IS NULL AND terminal_at IS NULL
`

type MatchingInitialAdapterConnectionParams struct {
	SessionID        string
	ActiveGeneration int64
	ActiveExpiresAt  pgtype.Timestamptz
}

func (q *Queries) MatchingInitialAdapterConnection(ctx context.Context, arg MatchingInitialAdapterConnectionParams) (SessionAdapterConnection, error) {
	row := q.db.QueryRow(ctx, matchingInitialAdapterConnection, arg.SessionID, arg.ActiveGeneration, arg.ActiveExpiresAt)
	var i SessionAdapterConnection
	err := row.Scan(
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.AcceptedFence,
		&i.ActiveCredentialGeneration,
		&i.CredentialGenerationHighWatermark,
		&i.ActiveCredentialExpiresAt,
		&i.PendingCredentialGeneration,
		&i.PendingCredentialExpiresAt,
		&i.PriorRecoveryCredentialGeneration,
		&i.RotationID,
		&i.RevokedAt,
		&i.TerminalAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const prepareAdapterCredentialRotation = `-- name: PrepareAdapterCredentialRotation :one
UPDATE session_adapter_connections
SET pending_credential_generation = $1,
    pending_credential_expires_at = $2,
    rotation_id = $3,
    credential_generation_high_watermark = $1,
    updated_at = clock_timestamp()
WHERE session_id = $4
  AND active_credential_generation = $5
  AND connection_epoch = $6
  AND pending_credential_generation IS NULL
  AND $1::BIGINT > credential_generation_high_watermark
  AND active_credential_expires_at > clock_timestamp()
  AND $2::TIMESTAMPTZ > clock_timestamp()
  AND revoked_at IS NULL
  AND terminal_at IS NULL
RETURNING session_id, connection_epoch, accepted_fence, active_credential_generation, credential_generation_high_watermark, active_credential_expires_at, pending_credential_generation, pending_credential_expires_at, prior_recovery_credential_generation, rotation_id, revoked_at, terminal_at, created_at, updated_at
`

type PrepareAdapterCredentialRotationParams struct {
	PendingGeneration        pgtype.Int8
	PendingExpiresAt         pgtype.Timestamptz
	RotationID               pgtype.Text
	SessionID                string
	ExpectedActiveGeneration int64
	ExpectedEpoch            int64
}

func (q *Queries) PrepareAdapterCredentialRotation(ctx context.Context, arg PrepareAdapterCredentialRotationParams) (SessionAdapterConnection, error) {
	row := q.db.QueryRow(ctx, prepareAdapterCredentialRotation,
		arg.PendingGeneration,
		arg.PendingExpiresAt,
		arg.RotationID,
		arg.SessionID,
		arg.ExpectedActiveGeneration,
		arg.ExpectedEpoch,
	)
	var i SessionAdapterConnection
	err := row.Scan(
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.AcceptedFence,
		&i.ActiveCredentialGeneration,
		&i.CredentialGenerationHighWatermark,
		&i.ActiveCredentialExpiresAt,
		&i.PendingCredentialGeneration,
		&i.PendingCredentialExpiresAt,
		&i.PriorRecoveryCredentialGeneration,
		&i.RotationID,
		&i.RevokedAt,
		&i.TerminalAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const validateAdapterAdmission = `-- name: ValidateAdapterAdmission :one
SELECT session_id, connection_epoch, accepted_fence, active_credential_generation, credential_generation_high_watermark, active_credential_expires_at, pending_credential_generation, pending_credential_expires_at, prior_recovery_credential_generation, rotation_id, revoked_at, terminal_at, created_at, updated_at FROM session_adapter_connections
WHERE session_id = $1
  AND active_credential_generation = $2
  AND connection_epoch = $3
  AND accepted_fence = $4
  AND $5::BIGINT > accepted_fence
  AND active_credential_expires_at > clock_timestamp()
  AND revoked_at IS NULL
  AND terminal_at IS NULL
`

type ValidateAdapterAdmissionParams struct {
	SessionID            string
	CredentialGeneration int64
	ConnectionEpoch      int64
	AcceptedFence        int64
	GrantFence           int64
}

func (q *Queries) ValidateAdapterAdmission(ctx context.Context, arg ValidateAdapterAdmissionParams) (SessionAdapterConnection, error) {
	row := q.db.QueryRow(ctx, validateAdapterAdmission,
		arg.SessionID,
		arg.CredentialGeneration,
		arg.ConnectionEpoch,
		arg.AcceptedFence,
		arg.GrantFence,
	)
	var i SessionAdapterConnection
	err := row.Scan(
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.AcceptedFence,
		&i.ActiveCredentialGeneration,
		&i.CredentialGenerationHighWatermark,
		&i.ActiveCredentialExpiresAt,
		&i.PendingCredentialGeneration,
		&i.PendingCredentialExpiresAt,
		&i.PriorRecoveryCredentialGeneration,
		&i.RotationID,
		&i.RevokedAt,
		&i.TerminalAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
