// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachmentByID = `-- name: AttachmentByID :one
SELECT attach_id, bootstrap_session_id, target_session_id, status, delivery_state, delivery_version, queue_reason, expires_at, canceled_at, blocking_session_id, target_credential_lineage_ref, created_at, updated_at FROM session_attachments WHERE attach_id = $1
`

func (q *Queries) AttachmentByID(ctx context.Context, attachID string) (SessionAttachment, error) {
	row := q.db.QueryRow(ctx, attachmentByID, attachID)
	var i SessionAttachment
	err := row.Scan(
		&i.AttachID,
		&i.BootstrapSessionID,
		&i.TargetSessionID,
		&i.Status,
		&i.DeliveryState,
		&i.DeliveryVersion,
		&i.QueueReason,
		&i.ExpiresAt,
		&i.CanceledAt,
		&i.BlockingSessionID,
		&i.TargetCredentialLineageRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const attachmentByTarget = `-- name: AttachmentByTarget :one
SELECT attach_id, bootstrap_session_id, target_session_id, status, delivery_state, delivery_version, queue_reason, expires_at, canceled_at, blocking_session_id, target_credential_lineage_ref, created_at, updated_at FROM session_attachments WHERE target_session_id = $1
`

func (q *Queries) AttachmentByTarget(ctx context.Context, targetSessionID string) (SessionAttachment, error) {
	row := q.db.QueryRow(ctx, attachmentByTarget, targetSessionID)
	var i SessionAttachment
	err := row.Scan(
		&i.AttachID,
		&i.BootstrapSessionID,
		&i.TargetSessionID,
		&i.Status,
		&i.DeliveryState,
		&i.DeliveryVersion,
		&i.QueueReason,
		&i.ExpiresAt,
		&i.CanceledAt,
		&i.BlockingSessionID,
		&i.TargetCredentialLineageRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const attachmentStoreNow = `-- name: AttachmentStoreNow :one
SELECT clock_timestamp()::TIMESTAMPTZ
`

func (q *Queries) AttachmentStoreNow(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, attachmentStoreNow)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO session_attachments (
    attach_id, bootstrap_session_id, target_session_id, status, delivery_state,
    delivery_version, expires_at, target_credential_lineage_ref
) VALUES (
    $1, $2, $3,
    'join_pending', 'pending', 0, $4, $5
)
RETURNING attach_id, bootstrap_session_id, target_session_id, status, delivery_state, delivery_version, queue_reason, expires_at, canceled_at, blocking_session_id, target_credential_lineage_ref, created_at, updated_at
`

type InsertAttachmentParams struct {
	AttachID                   string
	BootstrapSessionID         string
	TargetSessionID            string
	ExpiresAt                  pgtype.Timestamptz
	TargetCredentialLineageRef string
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (SessionAttachment, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.AttachID,
		arg.BootstrapSessionID,
		arg.TargetSessionID,
		arg.ExpiresAt,
		arg.TargetCredentialLineageRef,
	)
	var i SessionAttachment
	err := row.Scan(
		&i.AttachID,
		&i.BootstrapSessionID,
		&i.TargetSessionID,
		&i.Status,
		&i.DeliveryState,
		&i.DeliveryVersion,
		&i.QueueReason,
		&i.ExpiresAt,
		&i.CanceledAt,
		&i.BlockingSessionID,
		&i.TargetCredentialLineageRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockAttachment = `-- name: LockAttachment :one
SELECT attach_id, bootstrap_session_id, target_session_id, status, delivery_state, delivery_version, queue_reason, expires_at, canceled_at, blocking_session_id, target_credential_lineage_ref, created_at, updated_at FROM session_attachments WHERE attach_id = $1 FOR UPDATE
`

func (q *Queries) LockAttachment(ctx context.Context, attachID string) (SessionAttachment, error) {
	row := q.db.QueryRow(ctx, lockAttachment, attachID)
	var i SessionAttachment
	err := row.Scan(
		&i.AttachID,
		&i.BootstrapSessionID,
		&i.TargetSessionID,
		&i.Status,
		&i.DeliveryState,
		&i.DeliveryVersion,
		&i.QueueReason,
		&i.ExpiresAt,
		&i.CanceledAt,
		&i.BlockingSessionID,
		&i.TargetCredentialLineageRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAttachment = `-- name: UpdateAttachment :one
UPDATE session_attachments
SET status = $1,
    delivery_state = $2,
    delivery_version = delivery_version + 1,
    queue_reason = $3,
    expires_at = $4,
    canceled_at = CASE WHEN $1 = 'canceled' THEN clock_timestamp() ELSE NULL END,
    blocking_session_id = $5,
    updated_at = clock_timestamp()
WHERE attach_id = $6
  AND delivery_version = $7
RETURNING attach_id, bootstrap_session_id, target_session_id, status, delivery_state, delivery_version, queue_reason, expires_at, canceled_at, blocking_session_id, target_credential_lineage_ref, created_at, updated_at
`

type UpdateAttachmentParams struct {
	Status            string
	DeliveryState     string
	QueueReason       pgtype.Text
	ExpiresAt         pgtype.Timestamptz
	BlockingSessionID pgtype.Text
	AttachID          string
	ExpectedVersion   int64
}

func (q *Queries) UpdateAttachment(ctx context.Context, arg UpdateAttachmentParams) (SessionAttachment, error) {
	row := q.db.QueryRow(ctx, updateAttachment,
		arg.Status,
		arg.DeliveryState,
		arg.QueueReason,
		arg.ExpiresAt,
		arg.BlockingSessionID,
		arg.AttachID,
		arg.ExpectedVersion,
	)
	var i SessionAttachment
	err := row.Scan(
		&i.AttachID,
		&i.BootstrapSessionID,
		&i.TargetSessionID,
		&i.Status,
		&i.DeliveryState,
		&i.DeliveryVersion,
		&i.QueueReason,
		&i.ExpiresAt,
		&i.CanceledAt,
		&i.BlockingSessionID,
		&i.TargetCredentialLineageRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
