// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attach_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachAttemptByJTIHash = `-- name: AttachAttemptByJTIHash :one
SELECT attempt_jti_hash, attach_id, bootstrap_session_id, target_session_id, provider, fingerprint_domain, fingerprint_version, fingerprint_digest, fingerprint_key_version, expires_at, admission_outcome, issued_credential_generation, created_at FROM session_attach_attempts WHERE attempt_jti_hash = $1
`

func (q *Queries) AttachAttemptByJTIHash(ctx context.Context, attemptJtiHash []byte) (SessionAttachAttempt, error) {
	row := q.db.QueryRow(ctx, attachAttemptByJTIHash, attemptJtiHash)
	var i SessionAttachAttempt
	err := row.Scan(
		&i.AttemptJtiHash,
		&i.AttachID,
		&i.BootstrapSessionID,
		&i.TargetSessionID,
		&i.Provider,
		&i.FingerprintDomain,
		&i.FingerprintVersion,
		&i.FingerprintDigest,
		&i.FingerprintKeyVersion,
		&i.ExpiresAt,
		&i.AdmissionOutcome,
		&i.IssuedCredentialGeneration,
		&i.CreatedAt,
	)
	return i, err
}

const attachAttemptStoreNow = `-- name: AttachAttemptStoreNow :one
SELECT clock_timestamp()::TIMESTAMPTZ
`

func (q *Queries) AttachAttemptStoreNow(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, attachAttemptStoreNow)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const insertAttachAttempt = `-- name: InsertAttachAttempt :one
INSERT INTO session_attach_attempts (
    attempt_jti_hash, attach_id, bootstrap_session_id, target_session_id, provider,
    fingerprint_domain, fingerprint_version, fingerprint_digest, fingerprint_key_version,
    expires_at, admission_outcome, issued_credential_generation
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12
)
ON CONFLICT (attempt_jti_hash) DO NOTHING
RETURNING attempt_jti_hash, attach_id, bootstrap_session_id, target_session_id, provider, fingerprint_domain, fingerprint_version, fingerprint_digest, fingerprint_key_version, expires_at, admission_outcome, issued_credential_generation, created_at
`

type InsertAttachAttemptParams struct {
	AttemptJtiHash             []byte
	AttachID                   string
	BootstrapSessionID         string
	TargetSessionID            string
	Provider                   string
	FingerprintDomain          string
	FingerprintVersion         int32
	FingerprintDigest          []byte
	FingerprintKeyVersion      int32
	ExpiresAt                  pgtype.Timestamptz
	AdmissionOutcome           string
	IssuedCredentialGeneration pgtype.Int8
}

func (q *Queries) InsertAttachAttempt(ctx context.Context, arg InsertAttachAttemptParams) (SessionAttachAttempt, error) {
	row := q.db.QueryRow(ctx, insertAttachAttempt,
		arg.AttemptJtiHash,
		arg.AttachID,
		arg.BootstrapSessionID,
		arg.TargetSessionID,
		arg.Provider,
		arg.FingerprintDomain,
		arg.FingerprintVersion,
		arg.FingerprintDigest,
		arg.FingerprintKeyVersion,
		arg.ExpiresAt,
		arg.AdmissionOutcome,
		arg.IssuedCredentialGeneration,
	)
	var i SessionAttachAttempt
	err := row.Scan(
		&i.AttemptJtiHash,
		&i.AttachID,
		&i.BootstrapSessionID,
		&i.TargetSessionID,
		&i.Provider,
		&i.FingerprintDomain,
		&i.FingerprintVersion,
		&i.FingerprintDigest,
		&i.FingerprintKeyVersion,
		&i.ExpiresAt,
		&i.AdmissionOutcome,
		&i.IssuedCredentialGeneration,
		&i.CreatedAt,
	)
	return i, err
}
