// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attention.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attentionSnapshot = `-- name: AttentionSnapshot :many
SELECT session_id, latest_seq, state, permission_id, permission_status,
       terminal_outcome, latest_change_seq, blocker_kind, blocker_reason,
       blocker_expires_at, blocking_session_id, blocker_operation,
       summary_version, last_durable_event_at, last_client_command_at,
       projection_state, created_at, updated_at
FROM session_attention_summaries
WHERE session_id = ANY($1::TEXT[])
ORDER BY session_id ASC
`

func (q *Queries) AttentionSnapshot(ctx context.Context, sessionIds []string) ([]SessionAttentionSummary, error) {
	rows, err := q.db.Query(ctx, attentionSnapshot, sessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionAttentionSummary
	for rows.Next() {
		var i SessionAttentionSummary
		if err := rows.Scan(
			&i.SessionID,
			&i.LatestSeq,
			&i.State,
			&i.PermissionID,
			&i.PermissionStatus,
			&i.TerminalOutcome,
			&i.LatestChangeSeq,
			&i.BlockerKind,
			&i.BlockerReason,
			&i.BlockerExpiresAt,
			&i.BlockingSessionID,
			&i.BlockerOperation,
			&i.SummaryVersion,
			&i.LastDurableEventAt,
			&i.LastClientCommandAt,
			&i.ProjectionState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attentionStoreNow = `-- name: AttentionStoreNow :one
SELECT clock_timestamp()::TIMESTAMPTZ
`

func (q *Queries) AttentionStoreNow(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, attentionStoreNow)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const attentionSummaryPage = `-- name: AttentionSummaryPage :many
SELECT session_id, latest_seq, state, permission_id, permission_status,
       terminal_outcome, latest_change_seq, blocker_kind, blocker_reason,
       blocker_expires_at, blocking_session_id, blocker_operation,
       summary_version, last_durable_event_at, last_client_command_at,
       projection_state, created_at, updated_at
FROM session_attention_summaries
WHERE session_id > $1::TEXT
  AND EXISTS (
      SELECT 1
      FROM session_adapter_connections AS authority
      WHERE authority.session_id = session_attention_summaries.session_id
        AND authority.active_credential_expires_at > clock_timestamp()
        AND authority.revoked_at IS NULL
        AND authority.terminal_at IS NULL
  )
ORDER BY session_id ASC
LIMIT $2::INT
`

type AttentionSummaryPageParams struct {
	AfterSessionID string
	PageLimit      int32
}

func (q *Queries) AttentionSummaryPage(ctx context.Context, arg AttentionSummaryPageParams) ([]SessionAttentionSummary, error) {
	rows, err := q.db.Query(ctx, attentionSummaryPage, arg.AfterSessionID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionAttentionSummary
	for rows.Next() {
		var i SessionAttentionSummary
		if err := rows.Scan(
			&i.SessionID,
			&i.LatestSeq,
			&i.State,
			&i.PermissionID,
			&i.PermissionStatus,
			&i.TerminalOutcome,
			&i.LatestChangeSeq,
			&i.BlockerKind,
			&i.BlockerReason,
			&i.BlockerExpiresAt,
			&i.BlockingSessionID,
			&i.BlockerOperation,
			&i.SummaryVersion,
			&i.LastDurableEventAt,
			&i.LastClientCommandAt,
			&i.ProjectionState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fenceAttentionTerminal = `-- name: FenceAttentionTerminal :exec
UPDATE session_adapter_connections
SET revoked_at = clock_timestamp(), terminal_at = clock_timestamp(), updated_at = clock_timestamp()
WHERE session_id = $1
  AND terminal_at IS NULL
`

func (q *Queries) FenceAttentionTerminal(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, fenceAttentionTerminal, sessionID)
	return err
}

const upsertAttentionEvent = `-- name: UpsertAttentionEvent :exec
INSERT INTO session_attention_summaries (
    session_id, latest_seq, state, permission_id, permission_status, terminal_outcome,
    latest_change_seq, last_durable_event_at, projection_state
) VALUES (
    $1, $2, COALESCE($3, 'starting'),
    $4::TEXT, CASE WHEN $4::TEXT IS NULL THEN NULL ELSE 'pending' END,
    $5::TEXT, $6, $7,
    CASE
		WHEN $2::BIGINT > 1 THEN 'incomplete'
        WHEN $8::BOOLEAN AND $3 IS NULL THEN 'incomplete'
        WHEN $3 IS NULL THEN 'incomplete'
        ELSE 'complete'
    END
)
ON CONFLICT (session_id) DO UPDATE
SET latest_seq = EXCLUDED.latest_seq,
    state = COALESCE($3, session_attention_summaries.state),
    permission_id = CASE
        WHEN NOT $9::BOOLEAN THEN session_attention_summaries.permission_id
        WHEN $4::TEXT IS NOT NULL THEN $4::TEXT
        WHEN session_attention_summaries.permission_id = $10::TEXT THEN NULL
        ELSE session_attention_summaries.permission_id
    END,
    permission_status = CASE
        WHEN NOT $9::BOOLEAN THEN session_attention_summaries.permission_status
        WHEN $4::TEXT IS NOT NULL THEN 'pending'
        WHEN session_attention_summaries.permission_id = $10::TEXT THEN NULL
        ELSE session_attention_summaries.permission_status
    END,
    terminal_outcome = COALESCE(session_attention_summaries.terminal_outcome, $5::TEXT),
    latest_change_seq = COALESCE(EXCLUDED.latest_change_seq, session_attention_summaries.latest_change_seq),
    last_durable_event_at = EXCLUDED.last_durable_event_at,
    projection_state = CASE
        WHEN session_attention_summaries.projection_state = 'incomplete' AND session_attention_summaries.latest_seq > 1 THEN 'incomplete'
        WHEN EXCLUDED.latest_seq <> session_attention_summaries.latest_seq + 1 THEN 'incomplete'
        WHEN $11::BOOLEAN THEN 'incomplete'
        WHEN $8::BOOLEAN AND $3 IS NULL THEN 'incomplete'
        WHEN session_attention_summaries.projection_state = 'incomplete' AND $8::BOOLEAN THEN 'complete'
        ELSE session_attention_summaries.projection_state
    END,
    updated_at = statement_timestamp()
WHERE session_attention_summaries.latest_seq < EXCLUDED.latest_seq
`

type UpsertAttentionEventParams struct {
	SessionID            string
	LatestSeq            int64
	EventState           interface{}
	PermissionID         pgtype.Text
	TerminalOutcome      pgtype.Text
	LatestChangeSeq      pgtype.Int8
	EventTime            pgtype.Timestamptz
	StateObserved        bool
	PermissionChange     bool
	PermissionDecisionID pgtype.Text
	ProjectionIncomplete bool
}

func (q *Queries) UpsertAttentionEvent(ctx context.Context, arg UpsertAttentionEventParams) error {
	_, err := q.db.Exec(ctx, upsertAttentionEvent,
		arg.SessionID,
		arg.LatestSeq,
		arg.EventState,
		arg.PermissionID,
		arg.TerminalOutcome,
		arg.LatestChangeSeq,
		arg.EventTime,
		arg.StateObserved,
		arg.PermissionChange,
		arg.PermissionDecisionID,
		arg.ProjectionIncomplete,
	)
	return err
}

const upsertAttentionLedger = `-- name: UpsertAttentionLedger :exec
INSERT INTO session_attention_summaries (
    session_id, state, blocker_kind, blocker_reason, blocker_expires_at,
    blocking_session_id, blocker_operation, summary_version,
    last_client_command_at, projection_state
) VALUES (
    $1, 'starting', $2, $3,
    $4, $5, $6,
    1, $7, 'incomplete'
)
ON CONFLICT (session_id) DO UPDATE
SET blocker_kind = $2,
    blocker_reason = $3,
    blocker_expires_at = $4,
    blocking_session_id = $5,
    blocker_operation = $6,
    summary_version = session_attention_summaries.summary_version + 1,
    last_client_command_at = COALESCE($7, session_attention_summaries.last_client_command_at),
    updated_at = statement_timestamp()
`

type UpsertAttentionLedgerParams struct {
	SessionID         string
	BlockerKind       pgtype.Text
	BlockerReason     pgtype.Text
	BlockerExpiresAt  pgtype.Timestamptz
	BlockingSessionID pgtype.Text
	BlockerOperation  pgtype.Text
	ClientCommandAt   pgtype.Timestamptz
}

func (q *Queries) UpsertAttentionLedger(ctx context.Context, arg UpsertAttentionLedgerParams) error {
	_, err := q.db.Exec(ctx, upsertAttentionLedger,
		arg.SessionID,
		arg.BlockerKind,
		arg.BlockerReason,
		arg.BlockerExpiresAt,
		arg.BlockingSessionID,
		arg.BlockerOperation,
		arg.ClientCommandAt,
	)
	return err
}
