// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attention_backfill.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attentionBackfillCheckpointExists = `-- name: AttentionBackfillCheckpointExists :one
SELECT EXISTS (SELECT 1 FROM session_event_streams AS checkpoint_stream WHERE checkpoint_stream.session_id = $1 UNION SELECT 1 FROM session_attachments AS checkpoint_attachment WHERE checkpoint_attachment.target_session_id = $1) AND NOT EXISTS (SELECT 1 FROM session_event_streams AS stream FULL JOIN session_attachments AS attachment ON attachment.target_session_id = stream.session_id LEFT JOIN session_attention_summaries AS summary ON summary.session_id = COALESCE(stream.session_id, attachment.target_session_id) WHERE COALESCE(stream.session_id, attachment.target_session_id) < $1 AND (summary.session_id IS NULL OR summary.projection_state = 'incomplete' OR summary.latest_seq <> COALESCE(stream.latest_seq, 0)))
`

func (q *Queries) AttentionBackfillCheckpointExists(ctx context.Context, checkpointSessionID string) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, attentionBackfillCheckpointExists, checkpointSessionID)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const backfillAttentionAttachment = `-- name: BackfillAttentionAttachment :one
SELECT status, delivery_state, delivery_version, queue_reason, expires_at, blocking_session_id FROM session_attachments WHERE target_session_id = $1
`

type BackfillAttentionAttachmentRow struct {
	Status            string
	DeliveryState     string
	DeliveryVersion   int64
	QueueReason       pgtype.Text
	ExpiresAt         pgtype.Timestamptz
	BlockingSessionID pgtype.Text
}

func (q *Queries) BackfillAttentionAttachment(ctx context.Context, sessionID string) (BackfillAttentionAttachmentRow, error) {
	row := q.db.QueryRow(ctx, backfillAttentionAttachment, sessionID)
	var i BackfillAttentionAttachmentRow
	err := row.Scan(
		&i.Status,
		&i.DeliveryState,
		&i.DeliveryVersion,
		&i.QueueReason,
		&i.ExpiresAt,
		&i.BlockingSessionID,
	)
	return i, err
}

const backfillAttentionEvents = `-- name: BackfillAttentionEvents :many
SELECT session_id, seq, (CASE WHEN octet_length(payload::text) > 1048576 THEN 'permission.request' ELSE type END)::text AS type, (CASE WHEN octet_length(payload::text) > 1048576 THEN '{}'::jsonb ELSE payload END)::jsonb AS payload, created_at FROM session_events WHERE session_id = $1 AND seq > $2 ORDER BY seq ASC LIMIT $3
`

type BackfillAttentionEventsParams struct {
	SessionID  string
	AfterSeq   int64
	EventLimit int32
}

type BackfillAttentionEventsRow struct {
	SessionID string
	Seq       int64
	Type      string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) BackfillAttentionEvents(ctx context.Context, arg BackfillAttentionEventsParams) ([]BackfillAttentionEventsRow, error) {
	rows, err := q.db.Query(ctx, backfillAttentionEvents, arg.SessionID, arg.AfterSeq, arg.EventLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackfillAttentionEventsRow
	for rows.Next() {
		var i BackfillAttentionEventsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backfillAttentionLedger = `-- name: BackfillAttentionLedger :one
SELECT MAX(created_at)::TIMESTAMPTZ AS last_client_command_at, COUNT(*)::BIGINT AS command_count, COUNT(*) FILTER (WHERE status = 'outcome_unknown')::BIGINT AS outcome_unknown_count FROM session_pending_commands WHERE session_id = $1
`

type BackfillAttentionLedgerRow struct {
	LastClientCommandAt pgtype.Timestamptz
	CommandCount        int64
	OutcomeUnknownCount int64
}

func (q *Queries) BackfillAttentionLedger(ctx context.Context, sessionID string) (BackfillAttentionLedgerRow, error) {
	row := q.db.QueryRow(ctx, backfillAttentionLedger, sessionID)
	var i BackfillAttentionLedgerRow
	err := row.Scan(&i.LastClientCommandAt, &i.CommandCount, &i.OutcomeUnknownCount)
	return i, err
}

const backfillAttentionSessions = `-- name: BackfillAttentionSessions :many
SELECT COALESCE(stream.session_id, attachment.target_session_id) AS session_id FROM session_event_streams AS stream FULL JOIN session_attachments AS attachment ON attachment.target_session_id = stream.session_id LEFT JOIN session_attention_summaries AS summary ON summary.session_id = COALESCE(stream.session_id, attachment.target_session_id) WHERE COALESCE(stream.session_id, attachment.target_session_id) > $1 AND (summary.session_id IS NULL OR summary.projection_state = 'incomplete' OR summary.latest_seq <> COALESCE(stream.latest_seq, 0)) ORDER BY COALESCE(stream.session_id, attachment.target_session_id) ASC LIMIT $2
`

type BackfillAttentionSessionsParams struct {
	AfterSessionID string
	SessionLimit   int32
}

func (q *Queries) BackfillAttentionSessions(ctx context.Context, arg BackfillAttentionSessionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, backfillAttentionSessions, arg.AfterSessionID, arg.SessionLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backfillAttentionStream = `-- name: BackfillAttentionStream :one
SELECT latest_seq, retention_gap, updated_at FROM session_event_streams WHERE session_id = $1
`

type BackfillAttentionStreamRow struct {
	LatestSeq    int64
	RetentionGap bool
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) BackfillAttentionStream(ctx context.Context, sessionID string) (BackfillAttentionStreamRow, error) {
	row := q.db.QueryRow(ctx, backfillAttentionStream, sessionID)
	var i BackfillAttentionStreamRow
	err := row.Scan(&i.LatestSeq, &i.RetentionGap, &i.UpdatedAt)
	return i, err
}

const ensureAttentionBackfillSummary = `-- name: EnsureAttentionBackfillSummary :exec
INSERT INTO session_attention_summaries (session_id, latest_seq, state, summary_version, last_client_command_at, projection_state) VALUES ($1, $2, 'starting', $3, $4, 'incomplete') ON CONFLICT (session_id) DO NOTHING
`

type EnsureAttentionBackfillSummaryParams struct {
	SessionID           string
	LatestSeq           int64
	SummaryVersion      int64
	LastClientCommandAt pgtype.Timestamptz
}

func (q *Queries) EnsureAttentionBackfillSummary(ctx context.Context, arg EnsureAttentionBackfillSummaryParams) error {
	_, err := q.db.Exec(ctx, ensureAttentionBackfillSummary,
		arg.SessionID,
		arg.LatestSeq,
		arg.SummaryVersion,
		arg.LastClientCommandAt,
	)
	return err
}

const finalizeAttentionBackfill = `-- name: FinalizeAttentionBackfill :exec
UPDATE session_attention_summaries SET projection_state = CASE WHEN $1::BOOLEAN OR $2::BOOLEAN THEN 'incomplete' ELSE projection_state END, updated_at = statement_timestamp() WHERE session_id = $3
`

type FinalizeAttentionBackfillParams struct {
	RetentionGap         bool
	ProjectionIncomplete bool
	SessionID            string
}

func (q *Queries) FinalizeAttentionBackfill(ctx context.Context, arg FinalizeAttentionBackfillParams) error {
	_, err := q.db.Exec(ctx, finalizeAttentionBackfill, arg.RetentionGap, arg.ProjectionIncomplete, arg.SessionID)
	return err
}

const resetAttentionForBackfill = `-- name: ResetAttentionForBackfill :one
UPDATE session_attention_summaries SET state = 'starting', permission_id = NULL, permission_status = NULL, terminal_outcome = NULL, latest_change_seq = NULL, last_durable_event_at = NULL, last_client_command_at = NULL, blocker_kind = NULL, blocker_reason = NULL, blocker_expires_at = NULL, blocking_session_id = NULL, blocker_operation = NULL, summary_version = 0, projection_state = 'complete', updated_at = statement_timestamp() WHERE session_id = $1 RETURNING latest_seq
`

func (q *Queries) ResetAttentionForBackfill(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, resetAttentionForBackfill, sessionID)
	var latest_seq int64
	err := row.Scan(&latest_seq)
	return latest_seq, err
}

const restoreAttentionBackfillActivity = `-- name: RestoreAttentionBackfillActivity :exec
UPDATE session_attention_summaries SET last_durable_event_at = $1, updated_at = statement_timestamp() WHERE session_id = $2
`

type RestoreAttentionBackfillActivityParams struct {
	LastDurableEventAt pgtype.Timestamptz
	SessionID          string
}

func (q *Queries) RestoreAttentionBackfillActivity(ctx context.Context, arg RestoreAttentionBackfillActivityParams) error {
	_, err := q.db.Exec(ctx, restoreAttentionBackfillActivity, arg.LastDurableEventAt, arg.SessionID)
	return err
}

const restoreAttentionBackfillAttachment = `-- name: RestoreAttentionBackfillAttachment :exec
UPDATE session_attention_summaries SET blocker_kind = $1, blocker_reason = $2, blocker_expires_at = $3, blocking_session_id = $4, blocker_operation = $5, projection_state = 'incomplete', updated_at = statement_timestamp() WHERE session_id = $6
`

type RestoreAttentionBackfillAttachmentParams struct {
	BlockerKind       pgtype.Text
	BlockerReason     pgtype.Text
	BlockerExpiresAt  pgtype.Timestamptz
	BlockingSessionID pgtype.Text
	BlockerOperation  pgtype.Text
	SessionID         string
}

func (q *Queries) RestoreAttentionBackfillAttachment(ctx context.Context, arg RestoreAttentionBackfillAttachmentParams) error {
	_, err := q.db.Exec(ctx, restoreAttentionBackfillAttachment,
		arg.BlockerKind,
		arg.BlockerReason,
		arg.BlockerExpiresAt,
		arg.BlockingSessionID,
		arg.BlockerOperation,
		arg.SessionID,
	)
	return err
}

const restoreAttentionBackfillLedger = `-- name: RestoreAttentionBackfillLedger :exec
UPDATE session_attention_summaries SET summary_version = GREATEST(summary_version, $1::BIGINT), last_client_command_at = $2, blocker_kind = CASE WHEN $3::BOOLEAN THEN 'outcome_unknown' ELSE blocker_kind END, blocker_reason = NULL, blocker_expires_at = NULL, blocking_session_id = NULL, blocker_operation = CASE WHEN $3::BOOLEAN THEN 'command' ELSE NULL END, updated_at = statement_timestamp() WHERE session_id = $4
`

type RestoreAttentionBackfillLedgerParams struct {
	SummaryVersion      int64
	LastClientCommandAt pgtype.Timestamptz
	HasOutcomeUnknown   bool
	SessionID           string
}

func (q *Queries) RestoreAttentionBackfillLedger(ctx context.Context, arg RestoreAttentionBackfillLedgerParams) error {
	_, err := q.db.Exec(ctx, restoreAttentionBackfillLedger,
		arg.SummaryVersion,
		arg.LastClientCommandAt,
		arg.HasOutcomeUnknown,
		arg.SessionID,
	)
	return err
}

const upsertAttentionBackfillEvent = `-- name: UpsertAttentionBackfillEvent :exec
INSERT INTO session_attention_summaries (session_id, latest_seq, state, permission_id, permission_status, terminal_outcome, latest_change_seq, last_durable_event_at, projection_state) VALUES ($1, $2, COALESCE($3, 'starting'), $4::TEXT, CASE WHEN $4::TEXT IS NULL THEN NULL ELSE 'pending' END, $5::TEXT, $6, $7, CASE WHEN $8::BOOLEAN THEN 'incomplete' ELSE 'complete' END) ON CONFLICT (session_id) DO UPDATE SET latest_seq = GREATEST(session_attention_summaries.latest_seq, EXCLUDED.latest_seq), state = COALESCE($3, session_attention_summaries.state), permission_id = CASE WHEN NOT $9::BOOLEAN THEN session_attention_summaries.permission_id WHEN $4::TEXT IS NOT NULL THEN $4::TEXT WHEN session_attention_summaries.permission_id = $10::TEXT THEN NULL ELSE session_attention_summaries.permission_id END, permission_status = CASE WHEN NOT $9::BOOLEAN THEN session_attention_summaries.permission_status WHEN $4::TEXT IS NOT NULL THEN 'pending' WHEN session_attention_summaries.permission_id = $10::TEXT THEN NULL ELSE session_attention_summaries.permission_status END, terminal_outcome = COALESCE(session_attention_summaries.terminal_outcome, $5::TEXT), latest_change_seq = COALESCE(EXCLUDED.latest_change_seq, session_attention_summaries.latest_change_seq), last_durable_event_at = EXCLUDED.last_durable_event_at, projection_state = CASE WHEN session_attention_summaries.projection_state = 'incomplete' OR $8::BOOLEAN THEN 'incomplete' ELSE session_attention_summaries.projection_state END, updated_at = statement_timestamp()
`

type UpsertAttentionBackfillEventParams struct {
	SessionID            string
	LatestSeq            int64
	EventState           interface{}
	PermissionID         pgtype.Text
	TerminalOutcome      pgtype.Text
	LatestChangeSeq      pgtype.Int8
	EventTime            pgtype.Timestamptz
	ProjectionIncomplete bool
	PermissionChange     bool
	PermissionDecisionID pgtype.Text
}

func (q *Queries) UpsertAttentionBackfillEvent(ctx context.Context, arg UpsertAttentionBackfillEventParams) error {
	_, err := q.db.Exec(ctx, upsertAttentionBackfillEvent,
		arg.SessionID,
		arg.LatestSeq,
		arg.EventState,
		arg.PermissionID,
		arg.TerminalOutcome,
		arg.LatestChangeSeq,
		arg.EventTime,
		arg.ProjectionIncomplete,
		arg.PermissionChange,
		arg.PermissionDecisionID,
	)
	return err
}
