// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: command_ledger.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commandStoreNow = `-- name: CommandStoreNow :one
SELECT statement_timestamp()::TIMESTAMPTZ
`

func (q *Queries) CommandStoreNow(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, commandStoreNow)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const insertPendingCommand = `-- name: InsertPendingCommand :one
INSERT INTO session_pending_commands (
    session_id, cmd_id, type, event_seq, status, expires_at
) VALUES (
    $1, $2, $3, $4, 'pending', $5
)
RETURNING session_id, cmd_id, type, event_seq, status, expires_at, created_at, updated_at
`

type InsertPendingCommandParams struct {
	SessionID string
	CmdID     string
	Type      string
	EventSeq  int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertPendingCommand(ctx context.Context, arg InsertPendingCommandParams) (SessionPendingCommand, error) {
	row := q.db.QueryRow(ctx, insertPendingCommand,
		arg.SessionID,
		arg.CmdID,
		arg.Type,
		arg.EventSeq,
		arg.ExpiresAt,
	)
	var i SessionPendingCommand
	err := row.Scan(
		&i.SessionID,
		&i.CmdID,
		&i.Type,
		&i.EventSeq,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockCommandAuthority = `-- name: LockCommandAuthority :one
SELECT true AS current
FROM session_adapter_connections
WHERE session_id = $1
  AND connection_epoch = $2
  AND active_credential_generation = $3
  AND active_credential_expires_at > statement_timestamp()
  AND revoked_at IS NULL
  AND terminal_at IS NULL
FOR UPDATE
`

type LockCommandAuthorityParams struct {
	SessionID            string
	ConnectionEpoch      int64
	CredentialGeneration int64
}

func (q *Queries) LockCommandAuthority(ctx context.Context, arg LockCommandAuthorityParams) (bool, error) {
	row := q.db.QueryRow(ctx, lockCommandAuthority, arg.SessionID, arg.ConnectionEpoch, arg.CredentialGeneration)
	var current bool
	err := row.Scan(&current)
	return current, err
}

const lockPendingCommandForClaim = `-- name: LockPendingCommandForClaim :one
SELECT session_id, cmd_id, type, event_seq, status, expires_at, created_at, updated_at
FROM session_pending_commands
WHERE session_id = $1 AND cmd_id = $2
  AND expires_at > statement_timestamp()
FOR UPDATE
`

type LockPendingCommandForClaimParams struct {
	SessionID string
	CmdID     string
}

func (q *Queries) LockPendingCommandForClaim(ctx context.Context, arg LockPendingCommandForClaimParams) (SessionPendingCommand, error) {
	row := q.db.QueryRow(ctx, lockPendingCommandForClaim, arg.SessionID, arg.CmdID)
	var i SessionPendingCommand
	err := row.Scan(
		&i.SessionID,
		&i.CmdID,
		&i.Type,
		&i.EventSeq,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPendingCommandForResolve = `-- name: LockPendingCommandForResolve :one
SELECT session_id, cmd_id, type, event_seq, status, expires_at, created_at, updated_at
FROM session_pending_commands
WHERE session_id = $1 AND cmd_id = $2
FOR UPDATE
`

type LockPendingCommandForResolveParams struct {
	SessionID string
	CmdID     string
}

func (q *Queries) LockPendingCommandForResolve(ctx context.Context, arg LockPendingCommandForResolveParams) (SessionPendingCommand, error) {
	row := q.db.QueryRow(ctx, lockPendingCommandForResolve, arg.SessionID, arg.CmdID)
	var i SessionPendingCommand
	err := row.Scan(
		&i.SessionID,
		&i.CmdID,
		&i.Type,
		&i.EventSeq,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pendingCommandByID = `-- name: PendingCommandByID :one
SELECT session_id, cmd_id, type, event_seq, status, expires_at, created_at, updated_at
FROM session_pending_commands
WHERE session_id = $1 AND cmd_id = $2
`

type PendingCommandByIDParams struct {
	SessionID string
	CmdID     string
}

func (q *Queries) PendingCommandByID(ctx context.Context, arg PendingCommandByIDParams) (SessionPendingCommand, error) {
	row := q.db.QueryRow(ctx, pendingCommandByID, arg.SessionID, arg.CmdID)
	var i SessionPendingCommand
	err := row.Scan(
		&i.SessionID,
		&i.CmdID,
		&i.Type,
		&i.EventSeq,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePendingCommandStatus = `-- name: UpdatePendingCommandStatus :one
UPDATE session_pending_commands
SET status = $1, updated_at = statement_timestamp()
WHERE session_id = $2
  AND cmd_id = $3
  AND status = $4
RETURNING session_id, cmd_id, type, event_seq, status, expires_at, created_at, updated_at
`

type UpdatePendingCommandStatusParams struct {
	Status         string
	SessionID      string
	CmdID          string
	ExpectedStatus string
}

func (q *Queries) UpdatePendingCommandStatus(ctx context.Context, arg UpdatePendingCommandStatusParams) (SessionPendingCommand, error) {
	row := q.db.QueryRow(ctx, updatePendingCommandStatus,
		arg.Status,
		arg.SessionID,
		arg.CmdID,
		arg.ExpectedStatus,
	)
	var i SessionPendingCommand
	err := row.Scan(
		&i.SessionID,
		&i.CmdID,
		&i.Type,
		&i.EventSeq,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
