// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: command_ledger.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commandAuthorityCurrent = `-- name: CommandAuthorityCurrent :one
SELECT EXISTS (
    SELECT 1
    FROM session_adapter_connections AS authority
    WHERE authority.session_id = $1
      AND authority.connection_epoch = $2
      AND authority.active_credential_generation = $3
      AND authority.active_credential_expires_at > clock_timestamp()
      AND authority.revoked_at IS NULL
      AND authority.terminal_at IS NULL
) AS current
`

type CommandAuthorityCurrentParams struct {
	SessionID            string
	ConnectionEpoch      int64
	CredentialGeneration int64
}

func (q *Queries) CommandAuthorityCurrent(ctx context.Context, arg CommandAuthorityCurrentParams) (bool, error) {
	row := q.db.QueryRow(ctx, commandAuthorityCurrent, arg.SessionID, arg.ConnectionEpoch, arg.CredentialGeneration)
	var current bool
	err := row.Scan(&current)
	return current, err
}

const commandStoreNow = `-- name: CommandStoreNow :one
SELECT clock_timestamp()::TIMESTAMPTZ
`

func (q *Queries) CommandStoreNow(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, commandStoreNow)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const insertPendingCommand = `-- name: InsertPendingCommand :one
INSERT INTO session_pending_commands (
    session_id, cmd_id, type, event_seq, status, expires_at
) SELECT
    $1, $2, $3, $4, 'pending', $5
FROM session_adapter_connections AS authority
WHERE authority.session_id = $1
  AND authority.connection_epoch = $6
  AND authority.active_credential_generation = $7
  AND authority.active_credential_expires_at > clock_timestamp()
  AND authority.revoked_at IS NULL
  AND authority.terminal_at IS NULL
  AND $5::TIMESTAMPTZ > clock_timestamp()
  AND $5::TIMESTAMPTZ <= clock_timestamp() + interval '30 seconds'
RETURNING session_id, cmd_id, type, event_seq, status, expires_at, created_at, updated_at
`

type InsertPendingCommandParams struct {
	SessionID            string
	CmdID                string
	Type                 string
	EventSeq             int64
	ExpiresAt            pgtype.Timestamptz
	ConnectionEpoch      int64
	CredentialGeneration int64
}

func (q *Queries) InsertPendingCommand(ctx context.Context, arg InsertPendingCommandParams) (SessionPendingCommand, error) {
	row := q.db.QueryRow(ctx, insertPendingCommand,
		arg.SessionID,
		arg.CmdID,
		arg.Type,
		arg.EventSeq,
		arg.ExpiresAt,
		arg.ConnectionEpoch,
		arg.CredentialGeneration,
	)
	var i SessionPendingCommand
	err := row.Scan(
		&i.SessionID,
		&i.CmdID,
		&i.Type,
		&i.EventSeq,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockCommandAuthority = `-- name: LockCommandAuthority :one
SELECT true AS current
FROM session_adapter_connections AS authority
WHERE authority.session_id = $1
  AND authority.connection_epoch = $2
  AND authority.active_credential_generation = $3
  AND authority.active_credential_expires_at > clock_timestamp()
  AND authority.revoked_at IS NULL
  AND authority.terminal_at IS NULL
FOR UPDATE
`

type LockCommandAuthorityParams struct {
	SessionID            string
	ConnectionEpoch      int64
	CredentialGeneration int64
}

func (q *Queries) LockCommandAuthority(ctx context.Context, arg LockCommandAuthorityParams) (bool, error) {
	row := q.db.QueryRow(ctx, lockCommandAuthority, arg.SessionID, arg.ConnectionEpoch, arg.CredentialGeneration)
	var current bool
	err := row.Scan(&current)
	return current, err
}

const lockPendingCommandForClaim = `-- name: LockPendingCommandForClaim :one
SELECT session_id, cmd_id, type, event_seq, status, expires_at, created_at, updated_at
FROM session_pending_commands
WHERE session_id = $1 AND cmd_id = $2
  AND expires_at > statement_timestamp()
FOR UPDATE
`

type LockPendingCommandForClaimParams struct {
	SessionID string
	CmdID     string
}

func (q *Queries) LockPendingCommandForClaim(ctx context.Context, arg LockPendingCommandForClaimParams) (SessionPendingCommand, error) {
	row := q.db.QueryRow(ctx, lockPendingCommandForClaim, arg.SessionID, arg.CmdID)
	var i SessionPendingCommand
	err := row.Scan(
		&i.SessionID,
		&i.CmdID,
		&i.Type,
		&i.EventSeq,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPendingCommandForResolve = `-- name: LockPendingCommandForResolve :one
SELECT session_id, cmd_id, type, event_seq, status, expires_at, created_at, updated_at
FROM session_pending_commands
WHERE session_id = $1 AND cmd_id = $2
FOR UPDATE
`

type LockPendingCommandForResolveParams struct {
	SessionID string
	CmdID     string
}

func (q *Queries) LockPendingCommandForResolve(ctx context.Context, arg LockPendingCommandForResolveParams) (SessionPendingCommand, error) {
	row := q.db.QueryRow(ctx, lockPendingCommandForResolve, arg.SessionID, arg.CmdID)
	var i SessionPendingCommand
	err := row.Scan(
		&i.SessionID,
		&i.CmdID,
		&i.Type,
		&i.EventSeq,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pendingCommandByID = `-- name: PendingCommandByID :one
SELECT session_id, cmd_id, type, event_seq, status, expires_at, created_at, updated_at
FROM session_pending_commands
WHERE session_id = $1 AND cmd_id = $2
`

type PendingCommandByIDParams struct {
	SessionID string
	CmdID     string
}

func (q *Queries) PendingCommandByID(ctx context.Context, arg PendingCommandByIDParams) (SessionPendingCommand, error) {
	row := q.db.QueryRow(ctx, pendingCommandByID, arg.SessionID, arg.CmdID)
	var i SessionPendingCommand
	err := row.Scan(
		&i.SessionID,
		&i.CmdID,
		&i.Type,
		&i.EventSeq,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePendingCommandStatus = `-- name: UpdatePendingCommandStatus :one
UPDATE session_pending_commands AS command
SET status = $1, updated_at = statement_timestamp()
WHERE command.session_id = $2
  AND command.cmd_id = $3
  AND command.status = $4
  AND (NOT $5::BOOLEAN OR command.expires_at > clock_timestamp())
  AND EXISTS (
      SELECT 1
      FROM session_adapter_connections AS authority
      WHERE authority.session_id = $2
        AND authority.connection_epoch = $6
        AND authority.active_credential_generation = $7
        AND authority.active_credential_expires_at > clock_timestamp()
        AND authority.revoked_at IS NULL
        AND authority.terminal_at IS NULL
  )
RETURNING command.session_id, command.cmd_id, command.type, command.event_seq, command.status, command.expires_at, command.created_at, command.updated_at
`

type UpdatePendingCommandStatusParams struct {
	Status               string
	SessionID            string
	CmdID                string
	ExpectedStatus       string
	RequireUnexpired     bool
	ConnectionEpoch      int64
	CredentialGeneration int64
}

func (q *Queries) UpdatePendingCommandStatus(ctx context.Context, arg UpdatePendingCommandStatusParams) (SessionPendingCommand, error) {
	row := q.db.QueryRow(ctx, updatePendingCommandStatus,
		arg.Status,
		arg.SessionID,
		arg.CmdID,
		arg.ExpectedStatus,
		arg.RequireUnexpired,
		arg.ConnectionEpoch,
		arg.CredentialGeneration,
	)
	var i SessionPendingCommand
	err := row.Scan(
		&i.SessionID,
		&i.CmdID,
		&i.Type,
		&i.EventSeq,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
