// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_proposals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertProposedEvent = `-- name: InsertProposedEvent :one
INSERT INTO session_events (session_id, seq, type, payload, proposal_id, created_at)
SELECT $1, $2, $3, $4,
       $5, $6
FROM session_adapter_connections AS authority
WHERE authority.session_id = $1
  AND authority.connection_epoch = $7
  AND authority.active_credential_generation = $8
  AND authority.active_credential_expires_at > clock_timestamp()
  AND authority.revoked_at IS NULL
  AND authority.terminal_at IS NULL
RETURNING session_id, seq, proposal_id
`

type InsertProposedEventParams struct {
	SessionID            string
	Seq                  int64
	EventType            string
	Payload              []byte
	ProposalID           pgtype.Text
	CreatedAt            pgtype.Timestamptz
	ConnectionEpoch      int64
	CredentialGeneration int64
}

type InsertProposedEventRow struct {
	SessionID  string
	Seq        int64
	ProposalID pgtype.Text
}

func (q *Queries) InsertProposedEvent(ctx context.Context, arg InsertProposedEventParams) (InsertProposedEventRow, error) {
	row := q.db.QueryRow(ctx, insertProposedEvent,
		arg.SessionID,
		arg.Seq,
		arg.EventType,
		arg.Payload,
		arg.ProposalID,
		arg.CreatedAt,
		arg.ConnectionEpoch,
		arg.CredentialGeneration,
	)
	var i InsertProposedEventRow
	err := row.Scan(&i.SessionID, &i.Seq, &i.ProposalID)
	return i, err
}

const proposedEventByID = `-- name: ProposedEventByID :one
SELECT session_id, seq, proposal_id,
       type = $1::TEXT
       AND payload = $2::JSONB
       AND created_at = $3::TIMESTAMPTZ AS matches
FROM session_events
WHERE session_id = $4
  AND proposal_id = $5
`

type ProposedEventByIDParams struct {
	EventType  string
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
	SessionID  string
	ProposalID pgtype.Text
}

type ProposedEventByIDRow struct {
	SessionID  string
	Seq        int64
	ProposalID pgtype.Text
	Matches    pgtype.Bool
}

func (q *Queries) ProposedEventByID(ctx context.Context, arg ProposedEventByIDParams) (ProposedEventByIDRow, error) {
	row := q.db.QueryRow(ctx, proposedEventByID,
		arg.EventType,
		arg.Payload,
		arg.CreatedAt,
		arg.SessionID,
		arg.ProposalID,
	)
	var i ProposedEventByIDRow
	err := row.Scan(
		&i.SessionID,
		&i.Seq,
		&i.ProposalID,
		&i.Matches,
	)
	return i, err
}
