// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSessionEvent = `-- name: InsertSessionEvent :exec
INSERT INTO session_events (session_id, seq, type, payload, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSessionEventParams struct {
	SessionID string
	Seq       int64
	Type      string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertSessionEvent(ctx context.Context, arg InsertSessionEventParams) error {
	_, err := q.db.Exec(ctx, insertSessionEvent,
		arg.SessionID,
		arg.Seq,
		arg.Type,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const latestSessionEventSeq = `-- name: LatestSessionEventSeq :one
SELECT COALESCE(MAX(seq), 0)::BIGINT
FROM session_events
WHERE session_id = $1
`

func (q *Queries) LatestSessionEventSeq(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, latestSessionEventSeq, sessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const lockSessionEventStream = `-- name: LockSessionEventStream :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) LockSessionEventStream(ctx context.Context, pgAdvisoryXactLock int64) error {
	_, err := q.db.Exec(ctx, lockSessionEventStream, pgAdvisoryXactLock)
	return err
}

const replaySessionEvents = `-- name: ReplaySessionEvents :many
SELECT session_id, seq, type, payload, created_at
FROM session_events
WHERE session_id = $1 AND seq > $2
ORDER BY seq ASC
`

type ReplaySessionEventsParams struct {
	SessionID string
	Seq       int64
}

type ReplaySessionEventsRow struct {
	SessionID string
	Seq       int64
	Type      string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ReplaySessionEvents(ctx context.Context, arg ReplaySessionEventsParams) ([]ReplaySessionEventsRow, error) {
	rows, err := q.db.Query(ctx, replaySessionEvents, arg.SessionID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReplaySessionEventsRow
	for rows.Next() {
		var i ReplaySessionEventsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
