// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const reverseSessionEventPage = `-- name: ReverseSessionEventPage :many
SELECT session_id, seq, type, payload, created_at
FROM session_events
WHERE session_id = $1
  AND (
      $2::BIGINT IS NULL
      OR seq < $2::BIGINT
  )
ORDER BY seq DESC
LIMIT $3
`

type ReverseSessionEventPageParams struct {
	SessionID string
	BeforeSeq pgtype.Int8
	PageLimit int32
}

type ReverseSessionEventPageRow struct {
	SessionID string
	Seq       int64
	Type      string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ReverseSessionEventPage(ctx context.Context, arg ReverseSessionEventPageParams) ([]ReverseSessionEventPageRow, error) {
	rows, err := q.db.Query(ctx, reverseSessionEventPage, arg.SessionID, arg.BeforeSeq, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReverseSessionEventPageRow
	for rows.Next() {
		var i ReverseSessionEventPageRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionEventHistoryBounds = `-- name: SessionEventHistoryBounds :one
SELECT
    COALESCE(MIN(seq), 0)::BIGINT AS earliest_seq,
    COALESCE(MAX(seq), 0)::BIGINT AS latest_seq
FROM session_events
WHERE session_id = $1
`

type SessionEventHistoryBoundsRow struct {
	EarliestSeq int64
	LatestSeq   int64
}

func (q *Queries) SessionEventHistoryBounds(ctx context.Context, sessionID string) (SessionEventHistoryBoundsRow, error) {
	row := q.db.QueryRow(ctx, sessionEventHistoryBounds, sessionID)
	var i SessionEventHistoryBoundsRow
	err := row.Scan(&i.EarliestSeq, &i.LatestSeq)
	return i, err
}
