// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentSession struct {
	ID        string
	Provider  string
	Status    string
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
}

type SessionAdapterConnection struct {
	SessionID                         string
	ConnectionEpoch                   int64
	AcceptedFence                     int64
	ActiveCredentialGeneration        int64
	CredentialGenerationHighWatermark int64
	ActiveCredentialExpiresAt         pgtype.Timestamptz
	PendingCredentialGeneration       pgtype.Int8
	PendingCredentialExpiresAt        pgtype.Timestamptz
	PriorRecoveryCredentialGeneration pgtype.Int8
	RotationID                        pgtype.Text
	RevokedAt                         pgtype.Timestamptz
	TerminalAt                        pgtype.Timestamptz
	CreatedAt                         pgtype.Timestamptz
	UpdatedAt                         pgtype.Timestamptz
}

type SessionAttachAttempt struct {
	AttemptJtiHash             []byte
	AttachID                   string
	BootstrapSessionID         string
	TargetSessionID            string
	Provider                   string
	FingerprintDomain          string
	FingerprintVersion         int32
	FingerprintDigest          []byte
	FingerprintKeyVersion      int32
	ExpiresAt                  pgtype.Timestamptz
	AdmissionOutcome           string
	IssuedCredentialGeneration pgtype.Int8
	CreatedAt                  pgtype.Timestamptz
}

type SessionAttachment struct {
	AttachID                   string
	BootstrapSessionID         string
	TargetSessionID            string
	Status                     string
	DeliveryState              string
	DeliveryVersion            int64
	QueueReason                pgtype.Text
	ExpiresAt                  pgtype.Timestamptz
	CanceledAt                 pgtype.Timestamptz
	BlockingSessionID          pgtype.Text
	TargetCredentialLineageRef string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type SessionAttentionSummary struct {
	SessionID           string
	LatestSeq           int64
	State               string
	PermissionID        pgtype.Text
	PermissionStatus    pgtype.Text
	TerminalOutcome     pgtype.Text
	LatestChangeSeq     pgtype.Int8
	BlockerKind         pgtype.Text
	BlockerReason       pgtype.Text
	BlockerExpiresAt    pgtype.Timestamptz
	BlockingSessionID   pgtype.Text
	BlockerOperation    pgtype.Text
	SummaryVersion      int64
	LastDurableEventAt  pgtype.Timestamptz
	LastClientCommandAt pgtype.Timestamptz
	ProjectionState     string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type SessionEvent struct {
	ID         int64
	SessionID  string
	Seq        int64
	Type       string
	Payload    []byte
	ProposalID pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type SessionEventStream struct {
	SessionID    string
	LatestSeq    int64
	RetentionGap bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type SessionFileReferenceCapability struct {
	SessionID                  string
	CapabilityEventSeq         int64
	CapabilityFingerprint      string
	WriterConnectionEpoch      int64
	WriterCredentialGeneration int64
	WriterLeaseID              string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type SessionFileReferenceCommand struct {
	SessionID                  string
	CmdID                      string
	MessageID                  string
	CapabilityFingerprint      string
	RequestFingerprint         string
	ReferenceCount             int32
	ReservationVersion         int64
	DeliveryDeadline           pgtype.Timestamptz
	WriterConnectionEpoch      pgtype.Int8
	WriterCredentialGeneration pgtype.Int8
	WriterLeaseID              pgtype.Text
	Status                     string
	TerminalEventSeq           pgtype.Int8
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type SessionPendingCommand struct {
	SessionID string
	CmdID     string
	Type      string
	EventSeq  int64
	Status    string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type SessionRunControl struct {
	SessionID                  string
	CmdID                      string
	Operation                  string
	CapabilityVersion          int64
	ReservationVersion         int64
	PreControlState            string
	PreControlStateSeq         int64
	WriterConnectionEpoch      int64
	WriterCredentialGeneration int64
	WriterLeaseID              string
	Deadline                   pgtype.Timestamptz
	Status                     string
	TerminalEventSeq           pgtype.Int8
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type SessionRunControlCapability struct {
	SessionID                  string
	CapabilityEventSeq         int64
	CapabilityVersion          int64
	InterruptSupported         bool
	StopSupported              bool
	WriterConnectionEpoch      int64
	WriterCredentialGeneration int64
	WriterLeaseID              string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type SessionSettingsCapability struct {
	SessionID                  string
	CapabilityEventSeq         int64
	Fingerprint                string
	EffectiveModelID           string
	EffectiveReasoningEffortID pgtype.Text
	EffectivePermissionModeID  string
	CapabilityVersion          int64
	WriterConnectionEpoch      int64
	WriterCredentialGeneration int64
	WriterLeaseID              string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type SessionSettingsCommand struct {
	SessionID                          string
	CmdID                              string
	RequestFingerprint                 string
	RequestedModelID                   pgtype.Text
	RequestedReasoningEffortID         pgtype.Text
	RequestedPermissionModeID          pgtype.Text
	ReservationVersion                 int64
	DeliveryDeadline                   pgtype.Timestamptz
	OperationDeadline                  pgtype.Timestamptz
	WriterConnectionEpoch              int64
	WriterCredentialGeneration         int64
	WriterLeaseID                      string
	ReservedCapabilityEventSeq         int64
	ReservedFingerprint                string
	ReservedEffectiveModelID           string
	ReservedEffectiveReasoningEffortID pgtype.Text
	ReservedEffectivePermissionModeID  string
	Status                             string
	TerminalEventSeq                   pgtype.Int8
	CreatedAt                          pgtype.Timestamptz
	UpdatedAt                          pgtype.Timestamptz
}

type SessionSettingsLiveWriter struct {
	SessionID            string
	ConnectionEpoch      int64
	CredentialGeneration int64
	WriterLeaseID        string
}

type SessionWorkspaceLease struct {
	WorkspaceKey            string
	WorkerID                string
	SessionID               string
	ConnectionEpoch         int64
	CredentialGeneration    int64
	LeaseID                 string
	ChildParentWorkspaceKey pgtype.Text
	ChildCapabilityDigest   []byte
	ChildScopeExpiresAt     pgtype.Timestamptz
	Status                  string
	Version                 int64
	ExpiresAt               pgtype.Timestamptz
	ReservationExpiresAt    pgtype.Timestamptz
	QuarantineReason        pgtype.Text
	RecoveryState           string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	ReleasedAt              pgtype.Timestamptz
}
