// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_admission.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionAdmissionTruth = `-- name: SessionAdmissionTruth :one
SELECT id, provider, status, ended_at
FROM agent_sessions
WHERE id = $1
`

type SessionAdmissionTruthRow struct {
	ID       string
	Provider string
	Status   string
	EndedAt  pgtype.Timestamptz
}

func (q *Queries) SessionAdmissionTruth(ctx context.Context, sessionID string) (SessionAdmissionTruthRow, error) {
	row := q.db.QueryRow(ctx, sessionAdmissionTruth, sessionID)
	var i SessionAdmissionTruthRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Status,
		&i.EndedAt,
	)
	return i, err
}
