// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_admission.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const projectAgentSessionState = `-- name: ProjectAgentSessionState :execrows
UPDATE agent_sessions
SET status = $1::text,
	ended_at = CASE
		WHEN $2::boolean THEN COALESCE(ended_at, $3::timestamptz)
		ELSE ended_at
	END
WHERE id = $4::text
	AND status NOT IN ('ended', 'error')
`

type ProjectAgentSessionStateParams struct {
	Status     string
	Terminal   bool
	ObservedAt pgtype.Timestamptz
	SessionID  string
}

func (q *Queries) ProjectAgentSessionState(ctx context.Context, arg ProjectAgentSessionStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, projectAgentSessionState,
		arg.Status,
		arg.Terminal,
		arg.ObservedAt,
		arg.SessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionAdmissionTruth = `-- name: SessionAdmissionTruth :one
SELECT id, provider, status, ended_at
FROM agent_sessions
WHERE id = $1
`

type SessionAdmissionTruthRow struct {
	ID       string
	Provider string
	Status   string
	EndedAt  pgtype.Timestamptz
}

func (q *Queries) SessionAdmissionTruth(ctx context.Context, sessionID string) (SessionAdmissionTruthRow, error) {
	row := q.db.QueryRow(ctx, sessionAdmissionTruth, sessionID)
	var i SessionAdmissionTruthRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Status,
		&i.EndedAt,
	)
	return i, err
}
