// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warm_attach.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertWarmAttachPendingCommand = `-- name: InsertWarmAttachPendingCommand :one
INSERT INTO session_pending_commands (
    session_id, cmd_id, type, event_seq, status, expires_at
) SELECT
    $1, $2, 'session.send', $3,
    'pending', $4
WHERE $4::TIMESTAMPTZ > clock_timestamp()
  AND $4::TIMESTAMPTZ <= clock_timestamp() + interval '30 seconds'
RETURNING session_id, cmd_id, type, event_seq, status, expires_at, created_at, updated_at
`

type InsertWarmAttachPendingCommandParams struct {
	SessionID string
	CmdID     string
	EventSeq  int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertWarmAttachPendingCommand(ctx context.Context, arg InsertWarmAttachPendingCommandParams) (SessionPendingCommand, error) {
	row := q.db.QueryRow(ctx, insertWarmAttachPendingCommand,
		arg.SessionID,
		arg.CmdID,
		arg.EventSeq,
		arg.ExpiresAt,
	)
	var i SessionPendingCommand
	err := row.Scan(
		&i.SessionID,
		&i.CmdID,
		&i.Type,
		&i.EventSeq,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockWarmAttachBootstrap = `-- name: LockWarmAttachBootstrap :one
SELECT session_id, connection_epoch, accepted_fence, active_credential_generation, credential_generation_high_watermark, active_credential_expires_at, pending_credential_generation, pending_credential_expires_at, prior_recovery_credential_generation, rotation_id, revoked_at, terminal_at, created_at, updated_at FROM session_adapter_connections
WHERE session_id = $1
  AND active_credential_generation = $2
  AND connection_epoch = $3
  AND accepted_fence = $4
  AND connection_epoch > 0 AND accepted_fence > 0
  AND $5::BIGINT > accepted_fence
  AND active_credential_expires_at > clock_timestamp()
  AND revoked_at IS NULL
  AND terminal_at IS NULL
FOR UPDATE
`

type LockWarmAttachBootstrapParams struct {
	SessionID            string
	CredentialGeneration int64
	ConnectionEpoch      int64
	AcceptedFence        int64
	GrantFence           int64
}

func (q *Queries) LockWarmAttachBootstrap(ctx context.Context, arg LockWarmAttachBootstrapParams) (SessionAdapterConnection, error) {
	row := q.db.QueryRow(ctx, lockWarmAttachBootstrap,
		arg.SessionID,
		arg.CredentialGeneration,
		arg.ConnectionEpoch,
		arg.AcceptedFence,
		arg.GrantFence,
	)
	var i SessionAdapterConnection
	err := row.Scan(
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.AcceptedFence,
		&i.ActiveCredentialGeneration,
		&i.CredentialGenerationHighWatermark,
		&i.ActiveCredentialExpiresAt,
		&i.PendingCredentialGeneration,
		&i.PendingCredentialExpiresAt,
		&i.PriorRecoveryCredentialGeneration,
		&i.RotationID,
		&i.RevokedAt,
		&i.TerminalAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockWarmAttachTarget = `-- name: LockWarmAttachTarget :one
SELECT target.id
FROM agent_sessions AS target
WHERE target.id = $1
  AND NOT EXISTS (
      SELECT 1
      FROM session_attention_summaries AS summary
      WHERE summary.session_id = target.id
        AND (summary.state IN ('ended', 'error') OR summary.terminal_outcome IS NOT NULL)
  )
FOR UPDATE
`

func (q *Queries) LockWarmAttachTarget(ctx context.Context, targetSessionID string) (string, error) {
	row := q.db.QueryRow(ctx, lockWarmAttachTarget, targetSessionID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const warmAttachEventByTargetSeq = `-- name: WarmAttachEventByTargetSeq :one
SELECT session_id, seq, type, payload, created_at
FROM session_events
WHERE session_id = $1 AND seq = $2
`

type WarmAttachEventByTargetSeqParams struct {
	SessionID string
	EventSeq  int64
}

type WarmAttachEventByTargetSeqRow struct {
	SessionID string
	Seq       int64
	Type      string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) WarmAttachEventByTargetSeq(ctx context.Context, arg WarmAttachEventByTargetSeqParams) (WarmAttachEventByTargetSeqRow, error) {
	row := q.db.QueryRow(ctx, warmAttachEventByTargetSeq, arg.SessionID, arg.EventSeq)
	var i WarmAttachEventByTargetSeqRow
	err := row.Scan(
		&i.SessionID,
		&i.Seq,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const warmAttachStoreNow = `-- name: WarmAttachStoreNow :one
SELECT clock_timestamp()::TIMESTAMPTZ
`

func (q *Queries) WarmAttachStoreNow(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, warmAttachStoreNow)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}
