// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_leases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertWorkspaceLease = `-- name: InsertWorkspaceLease :one
INSERT INTO session_workspace_leases (
    workspace_key, worker_id, session_id, connection_epoch, credential_generation, lease_id,
    child_parent_workspace_key, child_capability_digest, child_scope_expires_at,
    status, version, expires_at, reservation_expires_at, recovery_state
)
SELECT
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    'reserved', 1, $10, $10, 'not_required'
WHERE $9::TIMESTAMPTZ IS NULL
   OR $9::TIMESTAMPTZ > clock_timestamp()
ON CONFLICT (workspace_key) DO NOTHING
RETURNING workspace_key, worker_id, session_id, connection_epoch, credential_generation, lease_id, child_parent_workspace_key, child_capability_digest, child_scope_expires_at, status, version, expires_at, reservation_expires_at, quarantine_reason, recovery_state, created_at, updated_at, released_at
`

type InsertWorkspaceLeaseParams struct {
	WorkspaceKey            string
	WorkerID                string
	SessionID               string
	ConnectionEpoch         int64
	CredentialGeneration    int64
	LeaseID                 string
	ChildParentWorkspaceKey pgtype.Text
	ChildCapabilityDigest   []byte
	ChildScopeExpiresAt     pgtype.Timestamptz
	ExpiresAt               pgtype.Timestamptz
}

func (q *Queries) InsertWorkspaceLease(ctx context.Context, arg InsertWorkspaceLeaseParams) (SessionWorkspaceLease, error) {
	row := q.db.QueryRow(ctx, insertWorkspaceLease,
		arg.WorkspaceKey,
		arg.WorkerID,
		arg.SessionID,
		arg.ConnectionEpoch,
		arg.CredentialGeneration,
		arg.LeaseID,
		arg.ChildParentWorkspaceKey,
		arg.ChildCapabilityDigest,
		arg.ChildScopeExpiresAt,
		arg.ExpiresAt,
	)
	var i SessionWorkspaceLease
	err := row.Scan(
		&i.WorkspaceKey,
		&i.WorkerID,
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.CredentialGeneration,
		&i.LeaseID,
		&i.ChildParentWorkspaceKey,
		&i.ChildCapabilityDigest,
		&i.ChildScopeExpiresAt,
		&i.Status,
		&i.Version,
		&i.ExpiresAt,
		&i.ReservationExpiresAt,
		&i.QuarantineReason,
		&i.RecoveryState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const quarantineWorkspaceLease = `-- name: QuarantineWorkspaceLease :one
UPDATE session_workspace_leases AS lease
SET status = 'quarantined', version = lease.version + 1, expires_at = NULL,
    quarantine_reason = 'authority_superseded', recovery_state = 'pending'
WHERE lease.workspace_key = $1
  AND lease.version = $2
  AND lease.status IN ('reserved', 'start_received')
RETURNING lease.workspace_key, lease.worker_id, lease.session_id, lease.connection_epoch, lease.credential_generation, lease.lease_id, lease.child_parent_workspace_key, lease.child_capability_digest, lease.child_scope_expires_at, lease.status, lease.version, lease.expires_at, lease.reservation_expires_at, lease.quarantine_reason, lease.recovery_state, lease.created_at, lease.updated_at, lease.released_at
`

type QuarantineWorkspaceLeaseParams struct {
	WorkspaceKey    string
	ExpectedVersion int64
}

func (q *Queries) QuarantineWorkspaceLease(ctx context.Context, arg QuarantineWorkspaceLeaseParams) (SessionWorkspaceLease, error) {
	row := q.db.QueryRow(ctx, quarantineWorkspaceLease, arg.WorkspaceKey, arg.ExpectedVersion)
	var i SessionWorkspaceLease
	err := row.Scan(
		&i.WorkspaceKey,
		&i.WorkerID,
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.CredentialGeneration,
		&i.LeaseID,
		&i.ChildParentWorkspaceKey,
		&i.ChildCapabilityDigest,
		&i.ChildScopeExpiresAt,
		&i.Status,
		&i.Version,
		&i.ExpiresAt,
		&i.ReservationExpiresAt,
		&i.QuarantineReason,
		&i.RecoveryState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const recordWorkspaceStartReceived = `-- name: RecordWorkspaceStartReceived :one
UPDATE session_workspace_leases AS lease
SET status = 'start_received', version = lease.version + 1, expires_at = NULL
FROM session_adapter_connections AS authority
JOIN session_attachments AS attachment ON attachment.target_session_id = authority.session_id
WHERE lease.workspace_key = $1
  AND lease.status = 'reserved'
  AND lease.version = $2
  AND (lease.worker_id, lease.session_id, lease.connection_epoch, lease.credential_generation, lease.lease_id)
      = ($3, $4, $5::BIGINT, $6::BIGINT, $7)
  AND lease.expires_at > clock_timestamp()
  AND (lease.child_scope_expires_at IS NULL OR lease.child_scope_expires_at > clock_timestamp())
  AND authority.session_id = lease.session_id
  AND authority.connection_epoch = lease.connection_epoch
  AND authority.active_credential_generation = lease.credential_generation
  AND authority.active_credential_expires_at > clock_timestamp()
  AND authority.revoked_at IS NULL
  AND authority.terminal_at IS NULL
  AND attachment.target_session_id = lease.session_id
  AND attachment.status IN ('queued', 'start_received')
  AND (attachment.expires_at IS NULL OR attachment.expires_at > clock_timestamp())
RETURNING lease.workspace_key, lease.worker_id, lease.session_id, lease.connection_epoch, lease.credential_generation, lease.lease_id, lease.child_parent_workspace_key, lease.child_capability_digest, lease.child_scope_expires_at, lease.status, lease.version, lease.expires_at, lease.reservation_expires_at, lease.quarantine_reason, lease.recovery_state, lease.created_at, lease.updated_at, lease.released_at
`

type RecordWorkspaceStartReceivedParams struct {
	WorkspaceKey         string
	ExpectedVersion      int64
	WorkerID             string
	SessionID            string
	ConnectionEpoch      int64
	CredentialGeneration int64
	LeaseID              string
}

func (q *Queries) RecordWorkspaceStartReceived(ctx context.Context, arg RecordWorkspaceStartReceivedParams) (SessionWorkspaceLease, error) {
	row := q.db.QueryRow(ctx, recordWorkspaceStartReceived,
		arg.WorkspaceKey,
		arg.ExpectedVersion,
		arg.WorkerID,
		arg.SessionID,
		arg.ConnectionEpoch,
		arg.CredentialGeneration,
		arg.LeaseID,
	)
	var i SessionWorkspaceLease
	err := row.Scan(
		&i.WorkspaceKey,
		&i.WorkerID,
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.CredentialGeneration,
		&i.LeaseID,
		&i.ChildParentWorkspaceKey,
		&i.ChildCapabilityDigest,
		&i.ChildScopeExpiresAt,
		&i.Status,
		&i.Version,
		&i.ExpiresAt,
		&i.ReservationExpiresAt,
		&i.QuarantineReason,
		&i.RecoveryState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const releaseWorkspaceLeaseAfterQuiescence = `-- name: ReleaseWorkspaceLeaseAfterQuiescence :one
UPDATE session_workspace_leases AS lease
SET status = 'released', version = lease.version + 1,
    expires_at = CASE WHEN lease.expires_at > clock_timestamp() THEN lease.expires_at
                      ELSE clock_timestamp() + interval '5 minutes' END,
    quarantine_reason = NULL, recovery_state = 'quiescent', released_at = clock_timestamp()
WHERE lease.workspace_key = $1
  AND lease.version = $2
  AND lease.status IN ('reserved', 'start_received', 'quarantined')
  AND (lease.worker_id, lease.session_id, lease.connection_epoch, lease.credential_generation, lease.lease_id)
      = ($3, $4, $5::BIGINT, $6::BIGINT, $7)
RETURNING lease.workspace_key, lease.worker_id, lease.session_id, lease.connection_epoch, lease.credential_generation, lease.lease_id, lease.child_parent_workspace_key, lease.child_capability_digest, lease.child_scope_expires_at, lease.status, lease.version, lease.expires_at, lease.reservation_expires_at, lease.quarantine_reason, lease.recovery_state, lease.created_at, lease.updated_at, lease.released_at
`

type ReleaseWorkspaceLeaseAfterQuiescenceParams struct {
	WorkspaceKey         string
	ExpectedVersion      int64
	WorkerID             string
	SessionID            string
	ConnectionEpoch      int64
	CredentialGeneration int64
	LeaseID              string
}

func (q *Queries) ReleaseWorkspaceLeaseAfterQuiescence(ctx context.Context, arg ReleaseWorkspaceLeaseAfterQuiescenceParams) (SessionWorkspaceLease, error) {
	row := q.db.QueryRow(ctx, releaseWorkspaceLeaseAfterQuiescence,
		arg.WorkspaceKey,
		arg.ExpectedVersion,
		arg.WorkerID,
		arg.SessionID,
		arg.ConnectionEpoch,
		arg.CredentialGeneration,
		arg.LeaseID,
	)
	var i SessionWorkspaceLease
	err := row.Scan(
		&i.WorkspaceKey,
		&i.WorkerID,
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.CredentialGeneration,
		&i.LeaseID,
		&i.ChildParentWorkspaceKey,
		&i.ChildCapabilityDigest,
		&i.ChildScopeExpiresAt,
		&i.Status,
		&i.Version,
		&i.ExpiresAt,
		&i.ReservationExpiresAt,
		&i.QuarantineReason,
		&i.RecoveryState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const reserveReleasedWorkspaceLease = `-- name: ReserveReleasedWorkspaceLease :one
UPDATE session_workspace_leases AS lease
SET worker_id = $1,
    session_id = $2,
    connection_epoch = $3,
    credential_generation = $4,
    lease_id = $5,
    child_parent_workspace_key = $6,
    child_capability_digest = $7,
    child_scope_expires_at = $8,
    status = 'reserved', version = lease.version + 1,
    expires_at = $9, reservation_expires_at = $9, quarantine_reason = NULL,
    recovery_state = 'not_required', released_at = NULL
WHERE lease.workspace_key = $10
  AND lease.status = 'released'
  AND ($8::TIMESTAMPTZ IS NULL OR $8::TIMESTAMPTZ > clock_timestamp())
RETURNING lease.workspace_key, lease.worker_id, lease.session_id, lease.connection_epoch, lease.credential_generation, lease.lease_id, lease.child_parent_workspace_key, lease.child_capability_digest, lease.child_scope_expires_at, lease.status, lease.version, lease.expires_at, lease.reservation_expires_at, lease.quarantine_reason, lease.recovery_state, lease.created_at, lease.updated_at, lease.released_at
`

type ReserveReleasedWorkspaceLeaseParams struct {
	WorkerID                string
	SessionID               string
	ConnectionEpoch         int64
	CredentialGeneration    int64
	LeaseID                 string
	ChildParentWorkspaceKey pgtype.Text
	ChildCapabilityDigest   []byte
	ChildScopeExpiresAt     pgtype.Timestamptz
	ExpiresAt               pgtype.Timestamptz
	WorkspaceKey            string
}

func (q *Queries) ReserveReleasedWorkspaceLease(ctx context.Context, arg ReserveReleasedWorkspaceLeaseParams) (SessionWorkspaceLease, error) {
	row := q.db.QueryRow(ctx, reserveReleasedWorkspaceLease,
		arg.WorkerID,
		arg.SessionID,
		arg.ConnectionEpoch,
		arg.CredentialGeneration,
		arg.LeaseID,
		arg.ChildParentWorkspaceKey,
		arg.ChildCapabilityDigest,
		arg.ChildScopeExpiresAt,
		arg.ExpiresAt,
		arg.WorkspaceKey,
	)
	var i SessionWorkspaceLease
	err := row.Scan(
		&i.WorkspaceKey,
		&i.WorkerID,
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.CredentialGeneration,
		&i.LeaseID,
		&i.ChildParentWorkspaceKey,
		&i.ChildCapabilityDigest,
		&i.ChildScopeExpiresAt,
		&i.Status,
		&i.Version,
		&i.ExpiresAt,
		&i.ReservationExpiresAt,
		&i.QuarantineReason,
		&i.RecoveryState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const workspaceLeaseByKey = `-- name: WorkspaceLeaseByKey :one
SELECT workspace_key, worker_id, session_id, connection_epoch, credential_generation, lease_id, child_parent_workspace_key, child_capability_digest, child_scope_expires_at, status, version, expires_at, reservation_expires_at, quarantine_reason, recovery_state, created_at, updated_at, released_at
FROM session_workspace_leases
WHERE workspace_key = $1
`

func (q *Queries) WorkspaceLeaseByKey(ctx context.Context, workspaceKey string) (SessionWorkspaceLease, error) {
	row := q.db.QueryRow(ctx, workspaceLeaseByKey, workspaceKey)
	var i SessionWorkspaceLease
	err := row.Scan(
		&i.WorkspaceKey,
		&i.WorkerID,
		&i.SessionID,
		&i.ConnectionEpoch,
		&i.CredentialGeneration,
		&i.LeaseID,
		&i.ChildParentWorkspaceKey,
		&i.ChildCapabilityDigest,
		&i.ChildScopeExpiresAt,
		&i.Status,
		&i.Version,
		&i.ExpiresAt,
		&i.ReservationExpiresAt,
		&i.QuarantineReason,
		&i.RecoveryState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleasedAt,
	)
	return i, err
}
